[package]
name = "rcgen"
version = "0.8.11"
authors = ["est31 <MTest31@outlook.com>"]
description = "Rust X.509 certificate generator"
repository = "https://github.com/est31/rcgen"
documentation = "https://docs.rs/rcgen"
license = "MIT OR Apache-2.0"
edition = "2015"
readme = "README.md"

[lib]
name = "rcgen"
path = "src/lib.rs"

[[bin]]
name = "rcgen"
path = "src/main.rs"
required-features = ["pem"]

[dependencies]
yasna = { version = "0.4", features = ["chrono", "std"] }
ring = "0.16"
pem = { version = "0.8", optional = true }
chrono = { version = "0.4.6", default-features = false }
x509-parser = { version = "0.9", features = ["verify"], optional = true }
zeroize = { version = "1.2", optional = true }

[features]
default = ["pem"]

[package.metadata.docs.rs]
features = ["x509-parser"]

[dev-dependencies]
openssl = "0.10"
x509-parser = { version = "0.9", features = ["verify"] }
webpki = { version = "0.22", features = ["std"] }
botan = { version = "0.8", features = ["vendored"] }
