[package]
name = "rcgen"
version = "0.8.1"
authors = ["est31 <MTest31@outlook.com>"]
description = "Rust X.509 certificate generator"
repository = "https://github.com/est31/rcgen"
documentation = "https://docs.rs/rcgen"
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
name = "rcgen"
path = "src/lib.rs"

[[bin]]
name = "rcgen"
path = "src/main.rs"
required-features = ["pem"]

[dependencies]
yasna = { version = "0.3.1", features = ["chrono"] }
ring = "0.16"
pem = { version = "0.7", optional = true }
chrono = { version = "0.4.6", default-features = false }
x509-parser = { version = "0.7", optional = true }

[features]
default = ["pem"]

[package.metadata.docs.rs]
features = ["x509-parser"]

[dev-dependencies]
openssl = "0.10"
webpki = "0.21"
